"""Convert the OpenFic brand SVG into Android vector drawables.

Android's `VectorDrawable` understands the same path syntax as SVG, so the brand mark can
ship as vectors instead of a pile of rasterised PNGs. Two outputs are needed:

  * `ic_launcher_foreground` — the mark scaled into the 72x72 safe zone of an adaptive
    icon's 108x108 viewport, which is what launchers actually mask.
  * `ic_openfic` — the artwork at its native size, for use inside the app.

Run from the repository root:
    python android/tools/svg_to_vector.py
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SVG_PATH = REPO_ROOT / "frontend" / "public" / "openfic.svg"
OUT_DIR = REPO_ROOT / "android" / "app" / "src" / "main" / "res" / "drawable"

# `rgb(13.729858%, 12.159729%, 12.548828%)` — the brand's near-black.
FILL_COLOR = "#FF231F20"

# Adaptive icons reserve the outer ring for masking; artwork must sit inside the centre
# 72x72 of the 108x108 viewport or launchers will crop it.
ADAPTIVE_VIEWPORT = 108.0
ADAPTIVE_SAFE_ZONE = 72.0


def read_svg() -> tuple[float, float, float, float, list[str]]:
    source = SVG_PATH.read_text(encoding="utf-8")

    view_box = re.search(r'viewBox="([^"]+)"', source)
    if view_box is None:
        raise SystemExit(f"no viewBox in {SVG_PATH}")
    min_x, min_y, width, height = (float(value) for value in view_box.group(1).split())

    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', source)
    if not paths:
        raise SystemExit(f"no <path> elements in {SVG_PATH}")

    return min_x, min_y, width, height, paths


def render(width: float, height: float, paths: list[str], groups: str) -> str:
    body = "\n".join(
        f'        <path\n'
        f'            android:fillColor="{FILL_COLOR}"\n'
        f'            android:pathData="{path.strip()}" />'
        for path in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by android/tools/svg_to_vector.py — edit the source SVG, not this file. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width:g}dp"\n'
        f'    android:height="{height:g}dp"\n'
        f'    android:viewportWidth="{width:g}"\n'
        f'    android:viewportHeight="{height:g}">\n'
        f"{groups}\n"
        "</vector>\n"
    )


def main() -> None:
    min_x, min_y, width, height, paths = read_svg()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Native-size artwork. The SVG's viewBox starts at an offset, and VectorDrawable has no
    # equivalent, so a group shifts the path coordinates back to the origin.
    native = (
        f'    <group android:translateX="{-min_x:g}" android:translateY="{-min_y:g}">\n'
        + "\n".join(
            f'        <path\n'
            f'            android:fillColor="{FILL_COLOR}"\n'
            f'            android:pathData="{path.strip()}" />'
            for path in paths
        )
        + "\n    </group>"
    )
    (OUT_DIR / "ic_openfic.xml").write_text(
        render(width, height, paths, native), encoding="utf-8"
    )

    # Adaptive foreground: same content, scaled and centred inside the safe zone. A group's
    # transform is translate * rotate * scale, so scaling by `factor` then translating by the
    # inset lands the artwork exactly in the middle.
    scale = ADAPTIVE_SAFE_ZONE / max(width, height)
    inset = (ADAPTIVE_VIEWPORT - ADAPTIVE_SAFE_ZONE) / 2
    adaptive_body = "\n".join(
        f'            <path\n'
        f'                android:fillColor="{FILL_COLOR}"\n'
        f'                android:pathData="{path.strip()}" />'
        for path in paths
    )
    adaptive = (
        f'    <group\n'
        f'        android:scaleX="{scale:g}"\n'
        f'        android:scaleY="{scale:g}"\n'
        f'        android:translateX="{inset:g}"\n'
        f'        android:translateY="{inset:g}">\n'
        f'        <group android:translateX="{-min_x:g}" android:translateY="{-min_y:g}">\n'
        f"{adaptive_body}\n"
        f"        </group>\n"
        f"    </group>"
    )
    (OUT_DIR / "ic_launcher_foreground.xml").write_text(
        render(ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT, paths, adaptive), encoding="utf-8"
    )

    print(f"wrote ic_openfic.xml and ic_launcher_foreground.xml ({len(paths)} paths)")


if __name__ == "__main__":
    main()
